buildscript {
    repositories {
        maven {
            url '/opt/maven-repo'
            metadataSources { gradleMetadata(); mavenPom() }
        }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
