# jvmargs 留空 => --no-daemon 时构建直接在启动器 JVM 内运行，不 fork 守护进程
# （proot 沙箱间歇性 fork ENOSYS，规避之）
org.gradle.workers.max=1
android.useAndroidX=true
org.gradle.parallel=false
kotlin.incremental=true
android.enableLint=false
org.gradle.caching=true
kotlin.compiler.execution.strategy=in-process
android.aapt2FromMavenOverride=/root/android-sdk/build-tools/34.0.0/aapt2
